package dev.emi.emi.planner;

import java.util.Map;

import dev.emi.emi.planner.compat.PlannerMachineCompatRegistry;
import net.minecraft.client.MinecraftClient;
import net.minecraft.client.resource.language.I18n;

public final class PlannerText {
	private static final Map<String, String> RU = Map.ofEntries(
		Map.entry("planner.title", "Производственная линия"),
		Map.entry("line", "Линия"),
		Map.entry("summary.external", "Внешние входы/сек"),
		Map.entry("summary.internal", "Внутренний поток/сек"),
		Map.entry("summary.outputs", "Чистый выход/сек"),
		Map.entry("targets", "Цели:"),
		Map.entry("balance", "РАСЧЕТ"),
		Map.entry("balanced", "ГОТОВО"),
		Map.entry("limited", "ЛИМИТ"),
		Map.entry("clear", "ОЧИСТИТЬ"),
		Map.entry("power", "Энергия"),
		Map.entry("header.mode", "РЕЖИМ"),
		Map.entry("header.machine", "МАШИНА"),
		Map.entry("header.cfg", "НАСТР"),
		Map.entry("header.mach", "МАШ"),
		Map.entry("header.par", "ПАР"),
		Map.entry("header.volt", "НАПР"),
		Map.entry("header.oc", "OC"),
		Map.entry("header.duration", "ВРЕМЯ"),
		Map.entry("header.rate", "СКОР"),
		Map.entry("header.recipe", "РЕЦЕПТ"),
		Map.entry("header.inputs", "ВХОДЫ/сек"),
		Map.entry("header.outputs", "ВЫХОДЫ/сек"),
		Map.entry("footer.standard_voltage", "Стандартное напряжение:"),
		Map.entry("footer.recipe_min", "Мин. рецепта"),
		Map.entry("footer.apply_all", "ВСЕМ"),
		Map.entry("footer.groups", "ГРУППЫ"),
		Map.entry("footer.voltage_hint", "Новые машины наследуют это напряжение; строку можно переопределить."),
		Map.entry("machine.settings", "Настройки машины"),
		Map.entry("machine.select", "Выбор машины"),
		Map.entry("machine.coils", "Катушки"),
		Map.entry("machine.select_coils", "Выбор катушек"),
		Map.entry("machine.parallel_control", "Контроль параллелей"),
		Map.entry("machine.coil_help", "Бонус катушек умножает время и EU/t"),
		Map.entry("machine.parallel_help", "Контроль параллелей повторяет значение PAR в строке"),
		Map.entry("machine.special_help", "Специальные параметры машины применяются к расчету линии"),
		Map.entry("machine.throughput_multiplier", "Текущий множитель пропускной способности"),
		Map.entry("groups.title", "Группы и связи"),
		Map.entry("groups.root", "Корень"),
		Map.entry("groups.new", "+ ГРУППА"),
		Map.entry("groups.child", "+ ДОЧЕРНЯЯ"),
		Map.entry("groups.delete", "УДАЛИТЬ"),
		Map.entry("groups.rename", "ИМЯ"),
		Map.entry("groups.rename_label", "Имя группы"),
		Map.entry("groups.collapse", "СВЕРНУТЬ"),
		Map.entry("groups.expand", "РАЗВЕРНУТЬ"),
		Map.entry("groups.collapsed", "свернуто"),
		Map.entry("groups.group_row", "ГРУППА"),
		Map.entry("groups.close", "ЗАКРЫТЬ"),
		Map.entry("groups.recipes", "Рецепты"),
		Map.entry("groups.links", "Связи"),
		Map.entry("groups.move_here", "СЮДА"),
		Map.entry("groups.in_group", "В ГРУППЕ"),
		Map.entry("groups.match", "MATCH"),
		Map.entry("groups.ignore", "IGNORE"),
		Map.entry("groups.match_help", "MATCH: ресурс должен замыкаться внутри этой группы"),
		Map.entry("groups.ignore_help", "IGNORE: ресурс может пройти в родительскую группу"),
		Map.entry("groups.empty_links", "Нет ресурсов, которые одновременно производятся и потребляются на этом уровне"),
		Map.entry("groups.empty_recipes", "В линии пока нет рецептов"),
		Map.entry("groups.tooltip", "Вложенные группы и правила связей ресурсов"),
		Map.entry("groups.tooltip2", "MATCH замыкает ресурс внутри группы; IGNORE передает его уровнем выше"),
		Map.entry("groups.drag_group", "Перемещение группы"),
		Map.entry("groups.invalid_drop", "Нельзя переместить группу внутрь самой себя"),
		Map.entry("groups.drop_root", "Переместить в Корень"),
		Map.entry("groups.drop_before", "Поставить перед"),
		Map.entry("groups.drop_after", "Поставить после"),
		Map.entry("groups.drop_inside", "Переместить внутрь"),
		Map.entry("groups.drag_recipe", "Перемещение рецепта"),
		Map.entry("groups.drop_recipe_group", "Переместить рецепт в"),
		Map.entry("groups.reorder_recipe", "Изменить порядок рецепта"),
		Map.entry("status.add_targets", "Нажмите на выход рецепта, чтобы добавить цель"),
		Map.entry("status.target_selected", "Цель выбрана. Нажмите РАСЧЕТ."),
		Map.entry("status.target_added", "Цель добавлена. Нажмите РАСЧЕТ."),
		Map.entry("status.target_changed", "Скорость цели изменена. Нажмите РАСЧЕТ."),
		Map.entry("status.target_removed", "Цель удалена. Нажмите РАСЧЕТ."),
		Map.entry("status.line_changed", "Линия изменена. Нажмите РАСЧЕТ."),
		Map.entry("status.choose_target", "Сначала выберите хотя бы одну цель"),
		Map.entry("status.no_recipes", "В линии нет рецептов"),
		Map.entry("status.missing_recipe", "Один из рецептов отсутствует"),
		Map.entry("status.target_blocked", "Ни один рецепт не выводит цель за пределы замкнутых групп"),
		Map.entry("status.infeasible", "Ограничения производственной линии несовместимы"),
		Map.entry("status.unbounded", "Решение производственной линии не ограничено"),
		Map.entry("status.failed", "Не удалось решить производственную линию"),
		Map.entry("status.positive_flow", "Не удалось построить положительный поток цели"),
		Map.entry("status.balanced_target", "Сбалансировано по цели"),
		Map.entry("status.balanced_targets", "Сбалансировано по всем целям"),
		Map.entry("status.residual", "Сбалансировано с остатком"),
		Map.entry("status.capacity_shortfall", "ограничения машин все еще дают нехватку мощности"),
		Map.entry("status.sizing_unavailable", "для части машин расчет количества недоступен"),
		Map.entry("status.machines_sized", "машины рассчитаны"),
		Map.entry("status.bottleneck", "Узкое место ограничивает производительность линии"),
		Map.entry("status.fixed_setup", "фиксированная конфигурация машин"),
		Map.entry("status.requested", "Запрошено"),
		Map.entry("status.achievable", "Достижимо"),
		Map.entry("status.bottleneck_label", "Узкое место"),
		Map.entry("status.restored", "Сбалансированные скорости восстановлены"),
		Map.entry("status.disabled", "Балансировка отключена"),
		Map.entry("summary.external_prefix", "Внешние входы/"),
		Map.entry("summary.internal_prefix", "Внутренний поток/"),
		Map.entry("summary.outputs_prefix", "Чистый выход/"),
		Map.entry("summary.goal_hint", "Клик по выходу: OUT-цель; Ctrl + клик по входу: IN-цель"),
		Map.entry("header.inputs_prefix", "ВХОДЫ/"),
		Map.entry("header.outputs_prefix", "ВЫХОДЫ/"),
		Map.entry("mode.balance", "БАЛ"),
		Map.entry("mode.auto", "АВТО"),
		Map.entry("mode.manual", "РУЧ"),
		Map.entry("common.on", "ВКЛ"),
		Map.entry("common.off", "ВЫКЛ"),
		Map.entry("common.auto", "АВТО"),
		Map.entry("common.fixed", "ФИКС"),
		Map.entry("common.none", "нет"),
		Map.entry("common.supported", "поддерживается"),
		Map.entry("common.not_supported", "не поддерживается"),
		Map.entry("footer.volt_short", "НАПР:"),
		Map.entry("footer.apply_short", "ВСЕМ"),
		Map.entry("footer.groups_short", "ГРУППЫ"),
		Map.entry("footer.tools", "ИНСТРУМЕНТЫ"),
		Map.entry("footer.undo_hint", "Ctrl+Z: Отмена"),
		Map.entry("footer.search_hint", "Ctrl+F: Поиск"),
		Map.entry("tools.export_line", "ЭКСПОРТ ЛИНИИ"),
		Map.entry("tools.import_line", "ИМПОРТ ЛИНИИ"),
		Map.entry("tools.time", "ВРЕМЯ"),
		Map.entry("tools.line_report", "ОТЧЕТ ЛИНИИ"),
		Map.entry("tools.recipe_changes", "ИЗМЕНЕНИЯ РЕЦЕПТОВ"),
		Map.entry("tools.tooltip", "Инструменты планировщика"),
		Map.entry("tools.tooltip_help", "Экспорт/импорт линии, единица времени и отчет по линии"),
		Map.entry("report.title", "Отчет по линии"),
		Map.entry("report.copy", "КОПИРОВАТЬ"),
		Map.entry("report.save", "СОХРАНИТЬ"),
		Map.entry("report.machines", "МАШИНЫ"),
		Map.entry("report.flows", "ПОТОКИ"),
		Map.entry("report.startup", "ЗАПУСК"),
		Map.entry("startup.title", "ЗАПУСК / ПЕРВИЧНОЕ ЗАПОЛНЕНИЕ"),
		Map.entry("startup.unit_hint", "MIN = минимум для запуска   BUF = буфер под текущую параллель"),
		Map.entry("startup.minimum", "Минимальный запас"),
		Map.entry("startup.buffer", "Рекомендуемый буфер"),
		Map.entry("startup.sources", "%s строк рецептов"),
		Map.entry("startup.none", "Катализаторы, возвращаемые ресурсы и замкнутые циклы не обнаружены"),
		Map.entry("startup.footer", "Запуск считается отдельно от постоянных потоков. CYCLE показывает выбранный стартовый ресурс для замкнутого цикла; заполнять каждый промежуточный ресурс не нужно."),
		Map.entry("startup.role.catalyst", "КАТАЛИЗАТОР"),
		Map.entry("startup.role.tool", "ИНСТРУМЕНТ"),
		Map.entry("startup.role.returned", "ВОЗВРАТ"),
		Map.entry("startup.role.container", "КОНТЕЙНЕР"),
		Map.entry("startup.role.cycle", "ЦИКЛ"),
		Map.entry("startup.role.consumed", "РАСХОД"),
		Map.entry("startup.desc.catalyst", "Вход явно возвращается рецептом в том же количестве: нужен для запуска, но не расходуется постоянно"),
		Map.entry("startup.desc.tool", "Многоразовый/изнашиваемый инструмент: считается для запуска, а не как расход в секунду"),
		Map.entry("startup.desc.returned", "Вход возвращает сам себя через remainder EMI и считается многоразовым ресурсом"),
		Map.entry("startup.desc.container", "Возвращаемая тара в замкнутом контуре: нужен начальный запас для циркуляции"),
		Map.entry("startup.desc.cycle", "Выбранный стартовый ресурс замкнутого цикла; остальные промежуточные ресурсы могут быть произведены после запуска"),
		Map.entry("startup.desc.consumed", "Обычный расходуемый ресурс"),
		Map.entry("report.display_unit", "Единица отображения"),
		Map.entry("report.total_machines", "Машины"),
		Map.entry("report.setups", "Конфигурации"),
		Map.entry("report.external_inputs", "Внешние входы"),
		Map.entry("report.net_outputs", "Чистые выходы"),
		Map.entry("report.average_power", "Средняя мощность"),
		Map.entry("report.recipe_rows", "строк рецептов"),
		Map.entry("report.provisional", "предварительный расчет"),
		Map.entry("report.no_machine_rows", "В этой линии нет активных строк машин"),
		Map.entry("report.no_flows", "В этой линии нет потоков"),
		Map.entry("report.footer", "КОПИРОВАТЬ/СОХРАНИТЬ экспортирует машины, цели, потоки, стартовые ресурсы и мощность."),
		Map.entry("report.copy_tooltip", "Скопировать полный отчет по линии"),
		Map.entry("report.copy_tooltip2", "Включает машины, цели, потоки, стартовые ресурсы и мощность"),
		Map.entry("report.save_tooltip", "Сохранить полный отчет по линии в .txt"),
		Map.entry("report.saved_to", "Сохраняется в config/emi-production-planner-exports"),
		Map.entry("report.voltage", "Напряжение"),
		Map.entry("report.parallel", "Параллель"),
		Map.entry("report.power_unknown", "Средняя мощность: частично неизвестна"),
		Map.entry("report.provisional_help", "Хотя бы одна строка использует предварительный/неизвестный расчет количества машин"),
		Map.entry("report.total_machines_text", "Всего машин"),
		Map.entry("report.distinct_setups", "Разных конфигураций"),
		Map.entry("report.recipe_rows_text", "Строк рецептов"),
		Map.entry("report.unknown_entries", " + строки с неизвестной мощностью"),
		Map.entry("report.targets", "ЦЕЛИ"),
		Map.entry("report.external_inputs_title", "ВНЕШНИЕ ВХОДЫ"),
		Map.entry("report.internal_flow_title", "ВНУТРЕННИЙ ПОТОК"),
		Map.entry("report.net_outputs_title", "ЧИСТЫЕ ВЫХОДЫ"),
		Map.entry("report.machines_title", "МАШИНЫ"),
		Map.entry("report.none", "нет"),
		Map.entry("report.power_unknown_short", "Мощность ?"),
		Map.entry("flow.in_target", "IN ЦЕЛЬ"),
		Map.entry("flow.out_target", "OUT ЦЕЛЬ"),
		Map.entry("flow.external_input", "ВНЕШНИЙ ВХОД"),
		Map.entry("flow.internal", "ВНУТРЕННИЙ ПОТОК"),
		Map.entry("flow.net_output", "ЧИСТЫЙ ВЫХОД"),
		Map.entry("migration.title", "Изменения рецептов"),
		Map.entry("migration.none", "Изменений рецептов не обнаружено"),
		Map.entry("migration.none_detail", "Сохраненные снимки рецептов совпадают с текущим реестром рецептов."),
		Map.entry("migration.summary", "%s изменено, %s отсутствует"),
		Map.entry("migration.changed", "ИЗМЕНЕН"),
		Map.entry("migration.missing", "ОТСУТСТВУЕТ"),
		Map.entry("migration.accept", "ПРИНЯТЬ"),
		Map.entry("migration.accept_all", "ПРИНЯТЬ ВСЕ"),
		Map.entry("migration.remove", "УДАЛИТЬ СТРОКУ"),
		Map.entry("migration.footer", "ПРИНЯТЬ сохраняет текущий рецепт как новую базовую версию. Отсутствующий рецепт нужно удалить или заменить."),
		Map.entry("migration.accepted", "Текущий рецепт принят как новая базовая версия"),
		Map.entry("migration.accepted_count", "Принято изменений рецептов: %s"),
		Map.entry("migration.removed", "Строка с отсутствующим рецептом удалена"),
		Map.entry("migration.unknown", "неизвестно"),
		Map.entry("migration.detail.inputs", "Входы"),
		Map.entry("migration.detail.outputs", "Выходы"),
		Map.entry("migration.detail.duration", "Время"),
		Map.entry("migration.detail.eut", "EU/t"),
		Map.entry("migration.detail.category", "Категория"),
		Map.entry("migration.detail.missing", "Рецепт больше не доступен в текущем реестре EMI"),
		Map.entry("migration.detail.last_output", "Сохраненный выход"),
		Map.entry("migration.impact.label", "Влияние"),
		Map.entry("migration.impact.output_capacity", "Выход той же конфигурации: %s/с -> %s/с"),
		Map.entry("migration.impact.autosize", "Авторазмер для %s крафт/с: МАШ %s ПАР %s -> МАШ %s ПАР %s"),
		Map.entry("migration.impact.power", "Средняя мощность на текущей скорости: %s -> %s EU/t"),
		Map.entry("migration.impact.none", "При текущей конфигурации немедленного влияния на скорость/энергию нет"),
		Map.entry("migration.line_impact.title", "ВЛИЯНИЕ НА ЛИНИЮ - текущие запланированные скорости"),
		Map.entry("migration.line_impact.machines", "Требуемые машины: %s -> %s"),
		Map.entry("migration.line_impact.power", "Средняя мощность: %s -> %s EU/t"),
		Map.entry("migration.line_impact.target", "Главная цель %s: %s -> %s%s"),
		Map.entry("migration.line_impact.target_same", "Главная цель %s: %s%s (без изменений)"),
		Map.entry("migration.line_impact.external", "Внешний вход: %s"),
		Map.entry("migration.line_impact.net", "Чистый выход: %s"),
		Map.entry("migration.line_impact.flows_same", "Потоки материалов не изменились при текущих запланированных скоростях"),
		Map.entry("migration.line_impact.missing", "%s текущих строк рецептов отсутствуют и исключены из новых итогов"),
		Map.entry("generic.prefix", "Generic GT - "),
		Map.entry("config.coil", "Катушка"),
		Map.entry("tooltip.path_cycle", "ПКМ: переключать глобальное правило пути (ПРЕДП -> ФИКС -> ИЗБЕГ -> ВЫКЛ)"),
		Map.entry("tooltip.path_current", "Глобальный путь: %s"),
		Map.entry("path.mode.prefer", "ПРЕДП"),
		Map.entry("path.mode.lock", "ФИКС"),
		Map.entry("path.mode.avoid", "ИЗБЕГ"),
		Map.entry("path.mode.off", "ВЫКЛ"),
		Map.entry("path.desc.prefer", "Автоподстановка предпочитает этот рецепт, но может выбрать другой, если этот недоступен"),
		Map.entry("path.desc.lock", "Автоподстановка может использовать только этот рецепт для данного ресурса"),
		Map.entry("path.desc.avoid", "Автоподстановка пропускает этот рецепт для данного ресурса"),
		Map.entry("path.desc.off", "Глобальное правило пути не задано"),
		Map.entry("tooltip.preferred", "Предпочтительная машина"),
		Map.entry("tooltip.set_preferred", "Сделать предпочтительной машиной"),
		Map.entry("tooltip.preferred_help", "Предпочтительная машина автоматически выбирается для новых рецептов этой категории"),
		Map.entry("tooltip.clear_preferred", "Клик: убрать предпочтение"),
		Map.entry("tooltip.save_preferred", "Клик: сохранить предпочтение"),
		Map.entry("tooltip.no_runtime", "Специальные runtime-модификаторы не обнаружены; используется математика Generic GT"),
		Map.entry("tooltip.new_line", "Новая производственная линия"),
		Map.entry("tooltip.rename_line", "ПКМ по вкладке линии: переименовать"),
		Map.entry("tooltip.delete_line", "Удалить активную производственную линию"),
		Map.entry("tooltip.input_goal", "IN-цель"),
		Map.entry("tooltip.output_target", "OUT-цель"),
		Map.entry("tooltip.achievable", "Достижимо"),
		Map.entry("tooltip.toggle_goal", "Ctrl + ЛКМ: переключить IN / OUT цель"),
		Map.entry("tooltip.view_recipes", "ЛКМ: показать рецепты"),
		Map.entry("tooltip.view_uses", "ПКМ: показать применения"),
		Map.entry("tooltip.requested_input", "Запрошенная скорость внешнего входа"),
		Map.entry("tooltip.requested_output", "Запрошенная скорость целевого выхода"),
		Map.entry("tooltip.type_exact", "Клик: ввести точное количество за"),
		Map.entry("tooltip.items_fluids", "Предметы используют /%s; жидкости используют mB/%s"),
		Map.entry("tooltip.bottleneck", "Узкое место"),
		Map.entry("tooltip.remove_target", "Удалить цель"),
		Map.entry("tooltip.no_goals", "Нет целей балансировки"),
		Map.entry("tooltip.add_out_goal", "Клик по выходу рецепта: добавить OUT-цель"),
		Map.entry("tooltip.add_in_goal", "Ctrl + клик по входу: добавить IN-цель"),
		Map.entry("tooltip.recalculate", "Пересчитать баланс линии"),
		Map.entry("tooltip.autobalance", "Автобаланс линии"),
		Map.entry("tooltip.balance_match", "Сопоставляет внутренне производимые/потребляемые ресурсы"),
		Map.entry("tooltip.balance_solve", "и решает все выбранные цели с запрошенной скоростью"),
		Map.entry("tooltip.balance_locks", "Фиксированные MACH/PAR считаются жесткими ограничениями оборудования"),
		Map.entry("tooltip.balance_bottleneck", "Узкое место распространяется через все рецепты линии"),
		Map.entry("tooltip.requested", "Запрошено"),
		Map.entry("tooltip.targets_count", "Целей"),
		Map.entry("tooltip.achievable_throughput", "Достижимая пропускная способность"),
		Map.entry("tooltip.clear_targets", "Очистить все цели и выйти из режима балансировки"),
		Map.entry("tooltip.standard_voltage", "Стандартное напряжение машин"),
		Map.entry("tooltip.voltage_inherit", "Новые рецепты автоматически наследуют это напряжение"),
		Map.entry("tooltip.left_choose_tier", "ЛКМ: выбрать тир"),
		Map.entry("tooltip.right_recipe_min", "ПКМ: минимум рецепта"),
		Map.entry("tooltip.voltage_overrides_preserved", "Строки с индивидуальным VOLT сохраняются"),
		Map.entry("tooltip.apply_voltage", "Применить стандартное напряжение ко всем рецептам этой линии"),
		Map.entry("tooltip.apply_voltage2", "Сбрасывает индивидуальные VOLT и переводит все строки на настройку линии"),
		Map.entry("tooltip.export", "Экспортировать текущую производственную линию"),
		Map.entry("tooltip.export2", "Копирует полный JSON линии в буфер обмена"),
		Map.entry("tooltip.export3", "и записывает .json в config/emi-production-planner-exports"),
		Map.entry("tooltip.export4", "Включает рецепты, группы, цели, MACH/PAR/VOLT и Machine CFG"),
		Map.entry("tooltip.import", "Импортировать производственную линию из буфера обмена"),
		Map.entry("tooltip.import2", "Скопируйте экспортированный JSON и нажмите ИМПОРТ"),
		Map.entry("tooltip.import3", "Импортированный план создается как новая линия"),
		Map.entry("tooltip.import4", "Существующие линии не перезаписываются"),
		Map.entry("tooltip.time_unit", "Единица времени отображения"),
		Map.entry("tooltip.time_cycle", "Переключает /s -> /min -> /h"),
		Map.entry("tooltip.time_math", "Меняется только отображение; расчеты планировщика остаются в секундах"),
		Map.entry("tooltip.recipe_changes", "Проверка обновлений рецептов"),
		Map.entry("tooltip.recipe_changes2", "Сравнивает сохраненные снимки рецептов с текущими рецептами сборки"),
		Map.entry("tooltip.recipe_changes3", "Находит изменения входов, выходов, времени, EU/t, категории и удаленные рецепты"),
		Map.entry("tooltip.build_summary", "Отчет по линии"),
		Map.entry("tooltip.build_summary2", "Показывает, сколько машин нужно построить для текущей линии"),
		Map.entry("tooltip.build_summary3", "Объединяет одинаковые VOLT / PAR / OC / Machine CFG"),
		Map.entry("tooltip.build_summary4", "Использует текущие MACH; BALANCE рассчитывает их автоматически"),
		Map.entry("tooltip.average_power", "Средняя мощность"),
		Map.entry("tooltip.power_calc", "Рассчитано из текущих скоростей рецептов и выбранных профилей машин"),
		Map.entry("tooltip.power_unavailable", "Мощность для этой линии недоступна"),
		Map.entry("tooltip.power_missing", "активных рецептов не имеют определенного GT EU/t"),
		Map.entry("tooltip.generic_fallback", "Профили без точных модификаторов пока используют математику Generic GT"),
		Map.entry("tooltip.right_rename", "ПКМ: переименовать"),
		Map.entry("tooltip.rate_bal", "Скорость BAL"),
		Map.entry("tooltip.rate_bal_help", "Скорость управляется автобалансом линии"),
		Map.entry("tooltip.rate_bal_exit", "Клик: выйти из BAL и вернуть AUTO/MAN скорости"),
		Map.entry("tooltip.rate_auto", "Скорость AUTO"),
		Map.entry("tooltip.rate_auto_help", "Показывается как крафты/%s; внутри считается в секунду"),
		Map.entry("tooltip.rate_to_manual", "Клик: переключить на ручную скорость"),
		Map.entry("tooltip.rate_manual", "Скорость MAN"),
		Map.entry("tooltip.rate_manual_help", "Прямое управление крафтами/%s"),
		Map.entry("tooltip.rate_to_auto", "Клик: переключить на автоматический расчет машины"),
		Map.entry("tooltip.duration_missing", "Длительность рецепта не определена"),
		Map.entry("tooltip.duration_set_first", "ПКМ по ВРЕМЯ: введите секунды перед включением АВТО"),
		Map.entry("tooltip.machine", "Машина"),
		Map.entry("tooltip.perfect_selectable", "Perfect OC: можно выбрать"),
		Map.entry("tooltip.perfect_unavailable", "Perfect OC: недоступен для этого профиля"),
		Map.entry("tooltip.selected_coils", "Выбранные катушки"),
		Map.entry("tooltip.parallel_setting", "Настройка Parallel Control"),
		Map.entry("tooltip.open_machine", "ЛКМ: открыть выбор машины"),
		Map.entry("tooltip.generic_gt", "ПКМ: Generic GT"),
		Map.entry("tooltip.compatible_profiles", "Совместимых профилей"),
		Map.entry("tooltip.machine_settings", "Специальные настройки машины"),
		Map.entry("tooltip.coils", "Катушки"),
		Map.entry("tooltip.configure_machine", "Клик: настроить эту машину"),
		Map.entry("tooltip.fixed_mach", "Фиксированное число машин"),
		Map.entry("tooltip.fixed_par", "Фиксированный parallel"),
		Map.entry("tooltip.left_toggle", "ЛКМ: переключить"),
		Map.entry("tooltip.balance_keep_mach", "BALANCE сохранит MACH = %s"),
		Map.entry("tooltip.balance_resize_mach", "BALANCE может автоматически изменить MACH"),
		Map.entry("tooltip.balance_keep_par", "BALANCE сохранит PAR = %s"),
		Map.entry("tooltip.balance_resize_par", "BALANCE может автоматически изменить PAR"),
		Map.entry("tooltip.machines", "Машины"),
		Map.entry("tooltip.mach_fixed", "MACH зафиксирован для BALANCE"),
		Map.entry("tooltip.mach_fix_help", "Кнопка F фиксирует MACH во время BALANCE"),
		Map.entry("tooltip.use_wheel", "Используйте +/- или колесо мыши"),
		Map.entry("tooltip.shift_10", "Shift изменяет на 10"),
		Map.entry("tooltip.right_exact", "ПКМ по числу: ввести точное значение"),
		Map.entry("tooltip.parallel_per_machine", "Parallel на машину"),
		Map.entry("tooltip.configured_max_parallel", "Настроенный максимум parallel"),
		Map.entry("tooltip.par_fixed", "PAR зафиксирован для BALANCE"),
		Map.entry("tooltip.par_fix_help", "Кнопка F фиксирует PAR во время BALANCE"),
		Map.entry("tooltip.machine_voltage", "Напряжение машины"),
		Map.entry("tooltip.recipe", "Рецепт"),
		Map.entry("tooltip.tier", "тир"),
		Map.entry("tooltip.overclocks", "Оверклоки"),
		Map.entry("tooltip.volt_fixed", "VOLT: зафиксирован выбранным профилем машины"),
		Map.entry("tooltip.volt_override", "VOLT: индивидуальная настройка строки"),
		Map.entry("tooltip.volt_inherited", "VOLT: унаследован от стандарта линии"),
		Map.entry("tooltip.open_voltage", "ЛКМ: открыть выбор напряжения"),
		Map.entry("tooltip.reset_voltage", "ПКМ: сбросить к стандарту линии"),
		Map.entry("tooltip.machine_profile", "Профиль машины"),
		Map.entry("tooltip.no_gt_eut", "GT EU/t для этого рецепта не определен"),
		Map.entry("tooltip.voltage_oc_disabled", "Оверклок по напряжению отключен для этой строки"),
		Map.entry("tooltip.oc_none", "Без оверклока по напряжению"),
		Map.entry("tooltip.oc_4x_duration", "Каждый OC: 4x EU/t, x%s длительность"),
		Map.entry("tooltip.oc_2x", "Каждый OC: 4x EU/t, 2x скорость"),
		Map.entry("tooltip.oc_4x", "Каждый OC: 4x EU/t, 4x скорость"),
		Map.entry("tooltip.oc_mode", "Режим OC"),
		Map.entry("tooltip.oc_next", "ЛКМ: следующий режим"),
		Map.entry("tooltip.oc_prev", "ПКМ: предыдущий режим"),
		Map.entry("tooltip.perfect_allowed", "Perfect OC разрешен этим профилем"),
		Map.entry("tooltip.perfect_denied", "Этот профиль машины не разрешает Perfect OC"),
		Map.entry("tooltip.base_duration", "Базовая длительность"),
		Map.entry("tooltip.not_detected", "не определена"),
		Map.entry("tooltip.after_oc", "После %s OC"),
		Map.entry("tooltip.processed_power", "Мощность после обработки"),
		Map.entry("tooltip.machine_settings_duration", "Настройки машины -> x%s длительность"),
		Map.entry("tooltip.machine_settings_throughput", "Настройки машины -> x%s пропускная способность"),
		Map.entry("tooltip.recipe_duration", "Длительность рецепта"),
		Map.entry("tooltip.recipe_duration_unavailable", "Длительность рецепта недоступна"),
		Map.entry("tooltip.manual_duration", "* Активна ручная базовая длительность"),
		Map.entry("tooltip.right_duration", "ПКМ: ввести базовую длительность в секундах"),
		Map.entry("tooltip.middle_reset_duration", "СКМ: сбросить к длительности рецепта"),
		Map.entry("tooltip.balanced_crafts", "Сбалансированные крафты"),
		Map.entry("tooltip.duration", "Длительность"),
		Map.entry("tooltip.resource_exact", "Поток ресурсов остается ровно на BAL-скорости; запас мощности машин не считается дополнительным выходом"),
		Map.entry("tooltip.return_auto_man", "Клик по BAL: вернуться к AUTO/MAN"),
		Map.entry("tooltip.crafts", "Крафты"),
		Map.entry("tooltip.machines_parallel", "%s машин x %s parallel / %s s"),
		Map.entry("tooltip.overclocks_power", "%s оверклок(ов), %s EU/t"),
		Map.entry("tooltip.edit_duration", "ПКМ: изменить базовую длительность"),
		Map.entry("tooltip.reset_duration", "СКМ: сбросить ручную длительность"),
		Map.entry("tooltip.switch_man", "Переключитесь на MAN для прямого изменения показанной скорости"),
		Map.entry("tooltip.manual_crafts", "Ручные крафты"),
		Map.entry("tooltip.mouse_wheel", "Колесо мыши: 1"),
		Map.entry("tooltip.modifiers", "Shift: 10   Ctrl: 0.1   Alt: 0.01"),
		Map.entry("tooltip.replace", "Заменить рецепт"),
		Map.entry("tooltip.replace2", "ЛКМ: открыть альтернативные рецепты для основного выхода этой строки"),
		Map.entry("tooltip.replace3", "Выберите рецепт и нажмите кнопку Planner, чтобы заменить строку"),
		Map.entry("tooltip.replace4", "Группа, MACH/PAR/VOLT и совместимый Machine CFG сохраняются"),
		Map.entry("tooltip.remove_recipe", "Удалить рецепт из линии"),
		Map.entry("flow.total_consumed", "Всего потребляется"),
		Map.entry("flow.total_produced", "Всего производится"),
		Map.entry("flow.internal_flow", "Внутренний поток"),
		Map.entry("flow.external_input_label", "Внешний вход"),
		Map.entry("flow.net_output_label", "Чистый выход"),
		Map.entry("flow.rate", "Скорость"),
		Map.entry("flow.expected", "Ожидаемое значение: задействован шанс или альтернативный ингредиент"),
		Map.entry("flow.already_goal", "Уже выбрано как цель линии"),
		Map.entry("flow.add_out", "ЛКМ: добавить как OUT-цель Auto-Balance"),
		Map.entry("flow.shift_recipes", "Shift + ЛКМ: показать рецепты"),
		Map.entry("flow.add_in", "Ctrl + ЛКМ: добавить как IN-цель"),
		Map.entry("sizing.unavailable_row", "Расчет количества машин недоступен для этой строки"),
		Map.entry("sizing.required_parallel", "Требуемый эффективный parallel"),
		Map.entry("sizing.constrained", "Ограниченная конфигурация"),
		Map.entry("sizing.recommended", "Рекомендуемая конфигурация"),
		Map.entry("sizing.setup", "%s машин(ы) x %s parallel"),
		Map.entry("sizing.installed_capacity", "Установленная производительность"),
		Map.entry("sizing.headroom", "Запас"),
		Map.entry("sizing.shortfall", "НЕХВАТКА МОЩНОСТИ"),
		Map.entry("sizing.locks", "Фиксации: MACH %s, PAR %s"),
		Map.entry("sizing.exact", "Расчет: точный по обнаруженному лимиту машины"),
		Map.entry("sizing.provisional", "Расчет: предварительный"),
		Map.entry("transfer.report_copied", "Отчет по линии скопирован в буфер обмена"),
		Map.entry("transfer.report_save_failed", "Не удалось сохранить отчет; используйте COPY"),
		Map.entry("transfer.saved", "Сохранено"),
		Map.entry("transfer.export_failed", "Ошибка экспорта"),
		Map.entry("transfer.json_copied", "JSON линии скопирован в буфер обмена"),
		Map.entry("transfer.exported", "Экспортировано %s + JSON скопирован в буфер обмена"),
		Map.entry("search.placeholder", "Поиск по текущей линии"),
		Map.entry("search.find", "Поиск:"),
		Map.entry("edit.crafts_per", "Крафтов за"),
		Map.entry("edit.machines", "Машины"),
		Map.entry("edit.parallel", "Parallel"),
		Map.entry("edit.duration_seconds", "Длительность, секунды"),
		Map.entry("time.second", "секунду"),
		Map.entry("time.minute", "минуту"),
		Map.entry("time.hour", "час"),
		Map.entry("planner.import.empty", "Буфер обмена пуст"),
		Map.entry("planner.import.not_json", "В буфере обмена нет JSON планировщика"),
		Map.entry("planner.import.no_line", "В JSON буфера обмена не найдена производственная линия"),
		Map.entry("planner.import.load_failed", "Не удалось загрузить импортированную линию"),
		Map.entry("planner.import.success", "Импортировано %s"),
		Map.entry("planner.import.invalid", "Некорректный JSON производственной линии"),
		Map.entry("planner.import.default_name", "Импортированная линия"),
		Map.entry("status.input_blocked", "Ни один рецепт в линии не потребляет IN-цель вне MATCH-групп"),
		Map.entry("machine.parallel_max", "Максимальный parallel на машину"),
		Map.entry("machine.parallel_unknown", "Лимит parallel зависит от профиля / пока не моделируется"),
		Map.entry("machine.fixed_voltage", "Фиксированное напряжение машины"),
		Map.entry("machine.perfect_oc", "Perfect OC"),
		Map.entry("machine.detected_max_parallel", "Обнаруженный максимум parallel"),
		Map.entry("machine.parallel_detected", "Поддержка Parallel Control обнаружена"),
		Map.entry("machine.duration_multiplier", "Множитель длительности машины"),
		Map.entry("machine.energy_multiplier", "Множитель энергии машины"),
		Map.entry("machine.coil_efficiency", "Эффективность катушек"),
		Map.entry("machine.coil_configurable", "Тир катушки настраивается в настройках машины"),
		Map.entry("machine.special_oc", "Особый OC: каждый 4x EU/t умножает длительность на x%s"),
		Map.entry("machine.setting_configurable", "%s настраивается в настройках машины"),
		Map.entry("sizing.note.fixed_both", "MACH и PAR зафиксированы игроком"),
		Map.entry("sizing.note.fixed_mach_max", "MACH зафиксирован; PAR рассчитан до обнаруженного максимума %s"),
		Map.entry("sizing.note.fixed_mach_provisional", "MACH зафиксирован; PAR предварительный, потому что лимит parallel машины неизвестен"),
		Map.entry("sizing.note.fixed_mach_one", "MACH зафиксирован; неизвестный лимит parallel консервативно считается равным 1"),
		Map.entry("sizing.note.fixed_par", "PAR зафиксирован; MACH рассчитан из фиксированного parallel"),
		Map.entry("sizing.note.fixed_par_provisional", "PAR зафиксирован; расчет MACH предварительный, потому что лимит parallel профиля неизвестен"),
		Map.entry("sizing.note.detected_max", "Рассчитано по обнаруженному максимуму parallel %s на машину"),
		Map.entry("sizing.note.parallel_control_unknown", "Parallel Control обнаружен, но его максимальный parallel неизвестен"),
		Map.entry("sizing.note.generic", "Generic-профиль предполагает, что требуемый эффективный parallel можно обеспечить"),
		Map.entry("sizing.note.conservative", "Лимит parallel неизвестен; консервативно считается 1 parallel на машину"),
		Map.entry("sizing.note.throughput", "; множитель пропускной способности машины x%s"),
		Map.entry("machine.sizing_unavailable", "Расчет количества машин недоступен"),
		Map.entry("machine.recipe_minimum", "Минимум рецепта"),
		Map.entry("machine.duration_eu_multiplier", "Множитель длительности/EU"),
		Map.entry("machine.detected_bonus", "Обнаруженный бонус"),
		Map.entry("machine.duration_eu_per_tier", "длительность/EU за тир (мультипликативно)"),
		Map.entry("machine.current_multiplier", "Текущий множитель"),
		Map.entry("machine.parallel_edit_help", "Используйте +/- здесь или меняйте PAR в строке рецепта"),
		Map.entry("machine.current_duration_multiplier", "Текущий множитель длительности"),
		Map.entry("gto.mod.perfect_oc", "GTO: поддержка Perfect OC обнаружена автоматически"),
		Map.entry("gto.mod.casing_limit", "GTO: ограничение тира рецепта по корпусу машины обнаружено автоматически"),
		Map.entry("gto.mod.glass_limit", "GTO: ограничение тира рецепта по стеклу обнаружено автоматически"),
		Map.entry("gto.mod.progression_duration", "GTO: бонус длительности от тира прогрессии обнаружен автоматически"),
		Map.entry("gto.mod.progression_parallel", "GTO: формула parallel от тира прогрессии обнаружена из байткода машины"),
		Map.entry("gto.mod.parallel_hatch", "GTO/GTM: Parallel Control Hatch обнаружен автоматически"),
		Map.entry("gto.mod.acceleration_hatch", "GTO: Acceleration Hatch обнаружен автоматически"),
		Map.entry("gto.mod.thread_hatch", "GTO: Thread Hatch обнаружен автоматически"),
		Map.entry("gto.mod.overclock_hatch", "GTO: Overclocking Hatch обнаружен автоматически"),
		Map.entry("gto.mod.laser_hatch", "GTO: поддержка Laser Energy Hatch обнаружена"),
		Map.entry("gto.mod.parallel_cap", "Эффективный лимит parallel Planner"),
		Map.entry("gto.mod.set_flux", "Задайте оба значения потока, чтобы применить обнаруженную runtime-формулу"),
		Map.entry("gto.mod.adjacent_count", "соседних"),
		Map.entry("gto.mod.cooling_supply", "Доступное охлаждение"),
		Map.entry("gto.mod.demand_parallel", "Потребность на parallel"),
		Map.entry("gto.mod.set_cooling", "Задайте тепловыделение рецепта, температуру реактора и число компонентов охлаждения, чтобы применить обнаруженный лимит"),
		Map.entry("gto.mod.tier_x", "Тир x"),
		Map.entry("gtceu.ebf.mod_heat", "GTCEu EBF: +100K за каждый выбранный тир напряжения выше MV"),
		Map.entry("gtceu.ebf.mod_discount", "GTCEu EBF: скидка x0.95 EU/t за каждые 900K выше температуры рецепта"),
		Map.entry("gtceu.ebf.mod_perfect", "GTCEu EBF: каждые 1800K выше температуры рецепта превращают один OC в perfect OC"),
		Map.entry("recipe.missing", "Отсутствует"),
		Map.entry("empty.add_recipe", "Откройте любой рецепт EMI и нажмите кнопку + Planner, чтобы добавить его в эту линию."),
		Map.entry("empty.mode_help", "Новые рецепты используют AUTO, если длительность определена; MAN оставляет прямое управление скоростью."),
		Map.entry("report.power_unknown_inline", "Мощность ?"),
		Map.entry("voltage.standard", "Стандартное напряжение"),
		Map.entry("voltage.select", "Выбор напряжения"),
		Map.entry("coil.base", "база"),
		Map.entry("coil.tier_above_cupronickel", "Тир выше Cupronickel"),
		Map.entry("edit.target_rate", "Скорость цели"),
		Map.entry("edit.line_name", "Имя линии"),
		Map.entry("profile.generic.description", "Любой рецепт; ручной резервный профиль"),
		Map.entry("profile.chemical_reactor.description", "Одноблочный Chemical Reactor"),
		Map.entry("profile.large_chemical_reactor.description", "Мультиблочный Chemical Reactor; точные правила parallel/катушек пока не моделируются"),
		Map.entry("profile.electrolyzer.description", "Одноблочный Electrolyzer"),
		Map.entry("profile.runtime.modeled", "Рабочая станция EMI; обнаруженные свойства машины применяются"),
		Map.entry("profile.runtime.generic", "Рабочая станция EMI; неизвестные бонусы используют математику Generic GT"),
		Map.entry("gto.mod.special_oc", "GTO: обнаружен особый множитель времени стандартного OC"),
		Map.entry("gto.mod.glass_parallel", "GTO: обнаружена формула встроенного parallel от тира стекла"),
		Map.entry("gto.mod.coil_parallel", "GTO: обнаружен parallel от катушки"),
		Map.entry("gto.mod.coil_log_parallel", "GTO: обнаружена логарифмическая формула parallel от катушки"),
		Map.entry("gto.mod.voltage_parallel", "GTO: обнаружена формула parallel от тира напряжения"),
		Map.entry("gto.mod.configured_parallel", "GTO: обнаружена формула parallel от настраиваемого тира"),
		Map.entry("gto.mod.glass_duration", "GTO: обнаружена формула длительности от тира стекла"),
		Map.entry("gto.mod.coil_duration_reduction", "GTO: обнаружено уменьшение длительности от тира катушки"),
		Map.entry("gto.mod.coil_energy_reduction", "GTO: обнаружено уменьшение энергии от тира катушки"),
		Map.entry("gto.mod.coil_temp_duration", "GTO: обнаружена формула длительности от температуры катушки"),
		Map.entry("gto.mod.coil_exp_duration", "GTO: обнаружена экспоненциальная формула длительности от температуры катушки"),
		Map.entry("gto.mod.aux_parallel", "GTO: обнаружен встроенный parallel Auxiliary Module"),
		Map.entry("gto.mod.aux_duration", "GTO: обнаружен множитель длительности Auxiliary Module"),
		Map.entry("gto.mod.count_duration", "GTO: обнаружена формула длительности по количеству"),
		Map.entry("gto.mod.structure_temp", "GTO: обнаружена механика структуры/температуры"),
		Map.entry("gto.mod.production_boost", "GTO: обнаружен режим Production-Boosting"),
		Map.entry("gto.mod.neutron_formula", "GTO: обнаружена формула длительности от нейтронного потока"),
		Map.entry("gto.mod.fission_cooling", "GTO: обнаружен лимит parallel по охлаждению деления"),
		Map.entry("gto.mod.tiers_above", "тиров выше"),
		Map.entry("bookmark.group.title", "Группа закладок"),
		Map.entry("bookmark.help.toggle_group_mode", "ЛКМ - Переключить режим группы"),
		Map.entry("bookmark.help.open_crafting_tree", "CTRL + ЛКМ - Открыть дерево крафта"),
		Map.entry("bookmark.help.toggle_crafting_chain", "ПКМ - Переключить цепочку крафта"),
		Map.entry("bookmark.help.send_to_chat", "CTRL + L - Отправить группу закладок в чат"),
		Map.entry("bookmark.help.toggle_collapse", "ALT + ЛКМ - Свернуть/развернуть"),
		Map.entry("bookmark.help.remove_group", "SHIFT + A - Удалить группу"),
		Map.entry("bookmark.help.craft_items", "SHIFT + C - Скрафтить предметы"),
		Map.entry("bookmark.help.open_exact_recipe", "ЛКМ по рецепту - Открыть точный рецепт"),
		Map.entry("bookmark.help.create_include_group", "ALT + ЛКМ + перетаскивание - Создать/добавить в группу"),
		Map.entry("bookmark.help.remove_exclude_group", "ПКМ + перетаскивание - Удалить/исключить из группы"),
		Map.entry("bookmark.help.change_recipe_quantity", "SHIFT/CTRL + колесо - Изменить количество рецепта"),
		Map.entry("bookmark.help.change_whole_group", "CTRL + SHIFT + колесо - Изменить всю группу"),
		Map.entry("bookmark.help.output_stack_step", "+ ALT - Шаг по размеру выходного стака"),
		Map.entry("bookmark.help.move_position", "SHIFT + ЛКМ + перетаскивание - Переместить позицию"),
		Map.entry("bookmark.help.reorder_item", "ЛКМ + перетаскивание по закладке - Изменить порядок"),
		Map.entry("bookmark.help.move_page", "SHIFT + ручка к < > - Переместить страницу"),
		Map.entry("bookmark.help.fill_ghost_slots", "SHIFT + ручка в слоты-фильтры - Заполнить группой"),
		Map.entry("bookmark.help.craft_missing", "CTRL + SHIFT + C - Скрафтить недостающие предметы"),
		Map.entry("bookmark.help.pull_bookmarked", "SHIFT + P - Забрать предметы из закладок"),
		Map.entry("bookmark.help.pull_missing", "CTRL + SHIFT + P - Забрать недостающие предметы"),
		Map.entry("bookmark.status.craft_missing", "Крафт недостающих: "),
		Map.entry("bookmark.status.crafting", "Крафт: "),
		Map.entry("bookmark.status.current", "Сейчас: "),
		Map.entry("bookmark.status.cancel_crafting", "SHIFT + C - Отменить крафт"),
		Map.entry("bookmark.status.me_craft_missing", "ME-крафт недостающих: "),
		Map.entry("bookmark.status.me_crafting", "ME-крафт: "),
		Map.entry("bookmark.status.pull_missing", "Получение недостающих: "),
		Map.entry("bookmark.status.pulling", "Получение: "),
		Map.entry("bookmark.status.cancel_pulling", "SHIFT + P - Отменить получение"),
		Map.entry("bookmark.chain.title", "Цепочка крафта"),
		Map.entry("bookmark.chain.results", "Результаты:"),
		Map.entry("bookmark.chain.missing_items", "Недостающие предметы:"),
		Map.entry("bookmark.chain.required_crafts", "Необходимые крафты:"),
		Map.entry("bookmark_tree.title", "Дерево крафта"),
		Map.entry("bookmark_tree.search", "Поиск"),
		Map.entry("bookmark_tree.search_hint", "Поиск..."),
		Map.entry("bookmark_tree.no_roots", "В этой группе закладок нет активных корневых рецептов"),
		Map.entry("bookmark_tree.hide_stats", "Скрыть панель статистики"),
		Map.entry("bookmark_tree.show_stats", "Показать панель статистики"),
		Map.entry("bookmark_tree.choose_sections", "Выбрать отображаемые разделы статистики"),
		Map.entry("bookmark_tree.save_image", "Сохранить дерево как изображение"),
		Map.entry("bookmark_tree.open_group", "Открыть другую группу закладок как дерево крафта"),
		Map.entry("bookmark_tree.close_tree", "Закрыть текущее дерево крафта"),
		Map.entry("bookmark_tree.rename_hint", "ПКМ: переименовать"),
		Map.entry("bookmark_tree.snapshot_recompute", "Пересчитать дерево с учетом инвентаря игрока (снимок)"),
		Map.entry("bookmark_tree.snapshot_clear", "Используется снимок инвентаря - клик для сброса"),
		Map.entry("bookmark_tree.fit_view", "Вписать дерево в экран"),
		Map.entry("bookmark_tree.collapse_done", "Свернуть предметы, для которых больше ничего не нужно крафтить"),
		Map.entry("bookmark_tree.requires_snapshot", "Требуется снимок инвентаря"),
		Map.entry("bookmark_tree.no_sections", "Не выбраны разделы статистики"),
		Map.entry("bookmark_tree.tree", "Дерево"),
		Map.entry("bookmark_tree.tree_number", "Дерево %s"),
		Map.entry("bookmark_tree.tree_name", "Имя дерева"),
		Map.entry("bookmark_tree.bookmark_group", "Группа закладок"),
		Map.entry("bookmark_tree.section.ingredients_needed", "Необходимые ингредиенты"),
		Map.entry("bookmark_tree.section.ingredients_available", "Доступные ингредиенты"),
		Map.entry("bookmark_tree.section.crafting_needed", "Нужно скрафтить"),
		Map.entry("bookmark_tree.section.crafting_available", "Доступно для крафта"),
		Map.entry("bookmark_tree.section.results", "Результаты"),
		Map.entry("bookmark_tree.section.remainders", "Остатки"),
		Map.entry("bookmark_tree.section.handlers", "Обработчики"),
		Map.entry("bookmark_tree.total", "Всего: %s"),
		Map.entry("bookmark_tree.missing", "Не хватает: %s"),
		Map.entry("bookmark_tree.crafts", "Крафтов: %s"),
		Map.entry("recipe_planner.title", "Планировщик производства"),
		Map.entry("recipe_planner.no_stable_id", "У этого рецепта нет стабильного ID, его нельзя сохранить"),
		Map.entry("recipe_planner.replace_title", "Заменить рецепт в планировщике производства"),
		Map.entry("recipe_planner.replace_lmb", "ЛКМ - Заменить выбранную строку планировщика этим рецептом"),
		Map.entry("recipe_planner.replace_preserve", "Сохраняет группу и совместимые настройки MACH / PAR / VOLT / CFG"),
		Map.entry("recipe_planner.replace_cancel", "ПКМ - Отменить замену и вернуться в планировщик"),
		Map.entry("recipe_planner.add_lmb", "ЛКМ - Добавить в активную линию (АВТО, если определено время рецепта)"),
		Map.entry("recipe_planner.open_rmb", "ПКМ - Открыть планировщик без добавления"),
		Map.entry("recipe_planner.replace_mismatch", "Режим замены: этот рецепт не производит %s"),
		Map.entry("recipe_planner.open_lines", "Открыть производственные линии"),
		Map.entry("recipe_overlay.title", "Действия с рецептом"),
		Map.entry("recipe_overlay.save_recipe", "SHIFT + A - Сохранить вместе с рецептом"),
		Map.entry("recipe_overlay.save_recipe_count", "CTRL + SHIFT + A - Сохранить с рецептом и количеством"),
		Map.entry("recipe_overlay.share_recipe", "CTRL + SHIFT + L - Отправить ссылку на рецепт в чат"),
		Map.entry("recipe_default.choose_outputs", "Выбрать выходы рецепта по умолчанию"),
		Map.entry("group.default", "Группа"),
		Map.entry("groups.auto", "AUTO"),
		Map.entry("groups.root_link_help", "AUTO: по возможности замыкать | MATCH: строго замыкать | IGNORE: не связывать потоки"),
		Map.entry("flow.link_mode", "Режим цикла"),
		Map.entry("flow.link_mode_hint", "СКМ: AUTO -> MATCH -> IGNORE"),
		Map.entry("tools.graph", "ГРАФ"),
		Map.entry("graph.title", "Граф производственной линии"),
		Map.entry("graph.back", "НАЗАД"),
		Map.entry("graph.fit", "ВПИСАТЬ"),
		Map.entry("graph.no_recipes", "Нет активных рецептов для построения графа"),
		Map.entry("graph.stats", "%s рецептов | %s потоков | масштаб %s%%"),
		Map.entry("graph.hint", "ЛКМ по узлу: открыть рецепт | перетаскивание: панорама | колесо: масштаб | F: вписать | Esc: назад"),
		Map.entry("graph.external", "Внешние"),
		Map.entry("graph.internal", "Внутренние"),
		Map.entry("graph.output", "Выход"),
		Map.entry("graph.external_input", "Внешний вход"),
		Map.entry("graph.net_output", "Чистый выход"),
		Map.entry("graph.target_input", "Целевой вход"),
		Map.entry("graph.target_output", "Целевой выход"),
		Map.entry("graph.back_help", "Вернуться в Production Planner"),
		Map.entry("graph.fit_help", "Вписать весь граф в экран"),
		Map.entry("graph.rate", "Скорость"),
		Map.entry("graph.group", "Группа"),
		Map.entry("graph.load", "Загрузка"),
		Map.entry("graph.open_recipe", "Нажмите, чтобы открыть рецепт"),
		Map.entry("graph.recipe", "Рецепт")
	);

	private PlannerText() {
	}

	public static String tr(String key, String english) {
		String translationKey = "emi.production_planner." + key;
		String translated = null;
		try {
			if (I18n.hasTranslation(translationKey)) {
				translated = I18n.translate(translationKey);
			}
		} catch (Throwable ignored) {
		}

		if (isRussian()) {
			if (translated != null && !translated.equals(english) && !translated.equals(translationKey)) {
				return translated;
			}
			String builtIn = RU.get(key);
			if (builtIn != null) {
				return builtIn;
			}
			String compat = PlannerMachineCompatRegistry.russianText(key);
			if (compat != null) {
				return compat;
			}
		}

		return translated != null && !translated.equals(translationKey) ? translated : english;
	}

	public static String tr(String key, String english, Object... args) {
		return String.format(tr(key, english), args);
	}

	public static boolean isRussian() {
		try {
			String language = MinecraftClient.getInstance().getLanguageManager().getLanguage();
			return language != null && language.toLowerCase().startsWith("ru");
		} catch (Throwable ignored) {
			return false;
		}
	}
}
